# Generated by Django 3.1.7 on 2021-03-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
